### ISSUE TITLE
Как настроить поддержку socks5?

### ISSUE THREAD

**Issue by wolfktl** [Saluev/python-telegram-dialog-bot#2]
Как настроить поддержку socks5?

**Comment by Saluev** [comment]
Не знаю) Надо разбираться.

**Comment by DemianS** [comment]
Привет  @wolfktl ! Уже поздно отвечать, но для будущих поколений ответим:
настройка socks не занимает много времени, всё что нужно, это вписать вот такой код до объявления Updater:
`"""PROXY"""`
`proxy_head = "socks5://"  # or socks5h://`
`proxy_address = "proxy_ip:port" # EDIT THIS with your porxy`
`proxy = proxy_head + proxy_address`

`REQUEST_KWARGS = {
    "proxy_url": proxy
}`

А затем в Updater запихиваем ещё один ключ **request_kwargs**

`self.updater = Updater(token=token, request_kwargs=REQUEST_KWARGS)`

Удачи!
