### ISSUE TITLE
Markup or Markdown? :)

### ISSUE THREAD

**Issue by DemianS** [Saluev/python-telegram-dialog-bot#3]
https://github.com/Saluev/python-telegram-dialog-bot/blob/67452559946ab9e8b6a8c57c2ef0df206134ab09/telegram_dialog/items.py#L13

Это ошибка или специальное упущение (easter egg)?) Имеется ввиду указание Markup заместо Markdown

**Comment by Saluev** [comment]
Ошибка, конечно) Можно было сразу пулл-реквест открывать.

**Comment by DemianS** [comment]
> Можно было сразу пулл-реквест открывать.

Я пока не разобрался как работает GitHub в этом плане. :) Только учусь.
Я как понимаю я мог создать pull requests и изменить самостоятельно ваш код? (погуглил теперь немного, вроде верно понял)

**Comment by Saluev** [comment]
Да, можно прямо в веб-интерфейсе кликнуть "Edit this file", отредактировать файл и жмякнуть внизу кнопку "Propose file change".
